# Generated by Django 3.0.7 on 2020-06-12 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, message='Name should be at most 50 characters long.'), django.core.validators.MinLengthValidator(3, message='Name should be at least 3 characters long.'), django.core.validators.ProhibitNullCharactersValidator(message='Name should not contain null characters.')])),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ should be in the standard format.', regex='/^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2}$/')])),
                ('city', models.CharField(default='Unknown', max_length=50, validators=[django.core.validators.MaxLengthValidator(50, message='Name should be at most 50 characters long.'), django.core.validators.MinLengthValidator(3, message='Name should be at least 3 characters long.'), django.core.validators.ProhibitNullCharactersValidator(message='Name should not contain null characters.')])),
            ],
        ),
    ]
