# Generated by Django 3.0.7 on 2020-06-14 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(default='Unknown', max_length=50, validators=[django.core.validators.MaxLengthValidator(50, message='This field should be at most 50 characters long.'), django.core.validators.MinLengthValidator(3, message='This field should be at least 3 characters long.'), django.core.validators.ProhibitNullCharactersValidator(message='This field should not contain null characters.')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ should be in the standard format.', regex='^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, message='This field should be at most 50 characters long.'), django.core.validators.MinLengthValidator(3, message='This field should be at least 3 characters long.'), django.core.validators.ProhibitNullCharactersValidator(message='This field should not contain null characters.')]),
        ),
    ]
