# Generated by Django 3.0.7 on 2020-06-14 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Field should follow the UPC-A standard format.', regex='^(?=.*0)[0-9]{12}$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, message='This field should be at most 50 characters long.'), django.core.validators.MinLengthValidator(3, message='This field should be at least 3 characters long.'), django.core.validators.ProhibitNullCharactersValidator(message='This field should not contain null characters.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('vendor', 'code'), name='unique products for each vendor'),
        ),
    ]
