# Generated by Django 3.0.7 on 2020-06-14 23:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200614_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Field should follow the UPC-A standard format.', regex='^(?=.*0)[0-9]{12}$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='Field should be at least 0.0.')]),
        ),
    ]
